apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-integrity-operator
  namespace: openshift-file-integrity
spec:
  replicas: 1
  selector:
    matchLabels:
      name: file-integrity-operator
  template:
    metadata:
      labels:
        name: file-integrity-operator
    spec:
      serviceAccountName: file-integrity-operator
      containers:
        - name: file-integrity-operator
          image: "quay.io/gquillar/file-integrity-operator:latest"
          command:
          - file-integrity-operator
          args:
          - operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "file-integrity-operator"
            - name: RELATED_IMAGE_OPERATOR
              value: "quay.io/gquillar/file-integrity-operator:latest"
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 120
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 120
